### ISSUE TITLE
[Improvment] Список задач. Добавление задач: изменить формат ввода данных в поля "Дата начала" и "Дата окончания"

### ISSUE THREAD

**Issue by DimaLinnik** [DimaLinnik/Testing_BSU#1]
Шаги:
1) Переходим на сайт https://cs-training-task.qulix.com/trainingtask3/
2) Нажимаем "Список задач"
3) Нажимаем "Добавить"

Получено:
Поля "Дата начала" и "Дата окончания" имеют возможность буквенного ввода

![image](https://user-images.githubusercontent.com/24574453/56889023-173fee00-6a7e-11e9-8b46-efb52c3f8c58.png)

Ожидается:
Календарный вид формы с невозможностью буквенного ввода

**Comment by vliplianina** [comment]
Замечания:
- неточный заголовок. С форматом ввода дат может быть связано несколько запросов на улучшение и дефектов и все будут подходить под данный заголовок. Поэтому требуется уточнение. Например: "Добавление задач: _изменить_  формат ввода данных в поля "Дата начала" и "Дата окончания"
- шаги должны быть пронумерованы
Нужно исправить.

Рекомендации:
- избыточно указывать скриншоты для каждого из шагов. Обычно такой подход используется для руководств пользователя, а не для технических специалистов команды разработки. Достаточно скриншота с полученным результатом

**Comment by DimaLinnik** [comment]
@vliplianina Замечания исправлены, запрос отредактирован в соответствии с полученными рекомендациями
