### ISSUE TITLE
[Improvment]Ввод задач: добавить отображение идентификатора

### ISSUE THREAD

**Issue by DimaLinnik** [DimaLinnik/Testing_BSU#2]
Шаги:
1) Переходим на сайт https://cs-training-task.qulix.com/trainingtask3/
2) Нажимаем "Список задач"
3) Нажимаем "Добавить"

Получено:
Два исполнителя с одинаковыми ФИО и отсутствие признаков различия
![image](https://user-images.githubusercontent.com/24574453/56889541-4c990b80-6a7f-11e9-8f7f-047c1dbec210.png)

Ожидается:
У каждого исполнителя отображается его идентификатор

**Comment by vliplianina** [comment]
Не является дефектом, т.к. не противоречит требованиями. Прошу переформулировать в запрос на улучшение с учётом замечаний, указанных в issue #1

**Comment by DimaLinnik** [comment]
@vliplianina запрос переформулирован, рекомендации внедрены, метки пересмотрены
