### ISSUE TITLE
[Improvment]Форма ввода проекта: выровнять название поля относительно верхнего края

### ISSUE THREAD

**Issue by DimaLinnik** [DimaLinnik/Testing_BSU#3]
Шаги:
1) Перейти https://cs-training-task.qulix.com/trainingtask3/project?projectEditMode=false&isSaved=false&isFirstEntry=true
2) Обратить внимание на расположение пункта "Описание"

Получено:
Пункт "Описание" находится в крайнем нижнем положении

Ожидаемо:
Пункт "Описание" находится в крайнем верхнем положении
![image](https://user-images.githubusercontent.com/24574453/57560431-0604b480-738f-11e9-9799-0a6d8b535c50.png)

**Comment by vliplianina** [comment]
Замечания:
- "Улучшение читабельности" - это следствие в результате внедрения улучшения. Подходит для аргументации в ожидаемом результате. 
Заголовок должен быть информативен и содержать информацию, что именно предлагается улучшить. В данном случае - выровнять название поле относительно середины поля.
- не описан шаг. Как минимум нужно перейти к форме и обратить внимание на определённый элемент

Рекомендация: с т.зр. юзабилити, лучше выровнять название поля относительно верхнего края, т.к. пользователи в нашем регионе читают слева направо и сверху вниз.

**Comment by DimaLinnik** [comment]
@vliplianina Замечания исправлены, запрос отредактирован в соответствии с полученными рекомендациями
