### ISSUE TITLE
[Improvment]Форма ввода проекта: увеличить отступ между полями "Сокращенное название" и "Описание"

### ISSUE THREAD

**Issue by DimaLinnik** [DimaLinnik/Testing_BSU#4]
Шаги:
1) Перейти https://cs-training-task.qulix.com/trainingtask3/project?projectEditMode=false&isSaved=false&isFirstEntry=true
2) Обратить внимание на отступ между полями "Сокращенное название" и "Описание"

Получено:
Отступ между полями "Сокращенное название" и "Описание" меньше чем отступ между полями "Название" и "Сокращенное название "
![image](https://user-images.githubusercontent.com/24574453/56890024-f331dc00-6a80-11e9-93b4-dc263e8b6b3c.png)

Ожидается:
Отступ между полями "Сокращенное название" и "Описание" увеличен и равен отступу между полями "Название" и "Сокращенное название "

**Comment by vliplianina** [comment]
Замечания:
- На скриншоте есть отступ между полями. Вероятно, предлагается увеличить отступ.
- Заголовок запроса на улучшение должен отвечать на вопрос "Что предлагается изменить?". В данном случае, заголовок сформулирован как для дефекта.  
- "Читабельность" не относится к характеристике расположения полей. Была бы актуальна читабельность текста при заполнении полей, если бы текст полей накладывался или сливался из-за отсутствия отступа, но такого поведения не наблюдается.

**Comment by DimaLinnik** [comment]
@vliplianina Замечания исправлены, запрос отредактирован в соответствии с полученными рекомендациями
