### ISSUE TITLE
[Improvment]Форма ввода проекта. Поле "Название": добавить преобразование строки в форму

### ISSUE THREAD

**Issue by DimaLinnik** [DimaLinnik/Testing_BSU#5]
Шаги:
1) Перейти https://cs-training-task.qulix.com/trainingtask3/project?projectEditMode=false&isSaved=false&isFirstEntry=true
2) Ввести 38 символов в поле "Название"

Получено:
При вводе текста, выходящего за рамки, происходит сдвиг видимого поля
![image](https://user-images.githubusercontent.com/24574453/56890211-84a14e00-6a81-11e9-94ef-5680fd70dcdb.png)

Ожидается:
При достижении 38 символов в строке, строка преобразуется в форму, визуально вмещающую в себя 255 символов

**Comment by vliplianina** [comment]
Замечания:
- переформулировать шаг
- исправить опечатку в слове "Ожимается"
- уточнить заголовок: кратко отразить информацию, указанную в ожидаемом результате

**Comment by DimaLinnik** [comment]
@vliplianina Замечания исправлены, запрос отредактирован в соответствии с полученными рекомендациями
